(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={client:null,session:null,players:[],currentPlayer:null,isAdmin:false,activeTab:"votes",weekStart:startWeek(new Date()),realtime:null};
const choices={yes:["Sì","S"],maybe:["Forse","F"],no:["No","N"]};
const longFmt=new Intl.DateTimeFormat("it-IT",{weekday:"long",day:"numeric",month:"long"}), shortFmt=new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit"}), histFmt=new Intl.DateTimeFormat("it-IT",{day:"numeric",month:"long",year:"numeric"});
document.addEventListener("DOMContentLoaded",init);
async function init(){bind();weekUi();try{const c=window.SERATA_LUDICA_CONFIG;if(!c?.SUPABASE_URL||!c?.SUPABASE_ANON_KEY)throw Error("Configurazione incompleta");state.client=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}});await session();await base();subscribe();await loadTab();}catch(e){toast(errText(e),true);}finally{$("#loading").classList.add("hidden");$("#app").setAttribute("aria-busy","false");}}
function bind(){$$("[data-tab]").forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$("#go-to-player").onclick=()=>openTab("players");$("#refresh-button").onclick=async()=>{await base();await loadTab();};$("#previous-week").onclick=()=>shift(-7);$("#next-week").onclick=()=>shift(7);$("#current-week").onclick=()=>setWeek(new Date());$("#week-input").onchange=e=>{const d=weekMonday(e.target.value);if(d)setWeek(d)};$("#claim-player-button").onclick=claim;$("#proposal-form").onsubmit=proposal;$("#result-form").onsubmit=record;$("#admin-login-form").onsubmit=adminLogin;$("#admin-logout").onclick=adminLogout;$("#add-player-form").onsubmit=addPlayer;}
async function session(){let r=await state.client.auth.getSession();if(r.error)throw r.error;state.session=r.data.session;if(!state.session){r=await state.client.auth.signInAnonymously();if(r.error)throw r.error;state.session=r.data.session;}return state.session;}
async function base(){await Promise.all([players(),currentPlayer(),adminState()]);renderPlayer();renderAdmin();}
async function players(){const r=await state.client.from("players").select("id,name,active").order("name");if(r.error)throw r.error;state.players=r.data||[];}
async function currentPlayer(){const u=(await session()).user.id,r=await state.client.from("app_user_players").select("user_id,players(id,name,active)").eq("user_id",u).limit(1);if(r.error)throw r.error;state.currentPlayer=r.data?.[0]?.players||null;}
async function adminState(){const r=await state.client.rpc("is_admin");if(r.error)throw r.error;state.isAdmin=r.data===true;}
function renderPlayer(){const active=state.players.filter(p=>p.active),sel=$("#player-select");$("#current-player-name").textContent=state.currentPlayer?.name||"Nessuno";sel.innerHTML='<option value="">Scegli…</option>'+active.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");if(state.currentPlayer){sel.value=state.currentPlayer.id;sel.disabled=true;$("#claim-player-button").disabled=true;}else{sel.disabled=false;$("#claim-player-button").disabled=false;}fillResult();}
function renderAdmin(){$("#admin-login-panel").classList.toggle("hidden",state.isAdmin);$("#admin-player-panel").classList.toggle("hidden",!state.isAdmin);$("#result-admin-panel").classList.toggle("hidden",!state.isAdmin);if(state.isAdmin&&state.activeTab==="players")adminPlayers();}
async function claim(){const id=$("#player-select").value;if(!id)return toast("Scegli un giocatore",true);const r=await state.client.rpc("claim_player",{p_player_id:id});if(r.error)return toast(errText(r.error),true);await currentPlayer();renderPlayer();toast("Giocatore associato");}
async function openTab(t){state.activeTab=t;$$('[data-tab]').forEach(b=>b.classList.toggle("active",b.dataset.tab===t));$$('[data-tab-panel]').forEach(p=>p.hidden=p.dataset.tabPanel!==t);await loadTab();}
async function loadTab(){try{if(state.activeTab==="votes")await loadVotes();if(state.activeTab==="summary")await summary();if(state.activeTab==="games")await proposals();if(state.activeTab==="ranking")await ranking();if(state.activeTab==="history")await history();if(state.activeTab==="players"&&state.isAdmin)await adminPlayers();}catch(e){toast(errText(e),true);}}
async function loadVotes(){let data=[];if(state.currentPlayer){const r=await state.client.from("votes").select("vote_date,choice").eq("week_start",iso(state.weekStart)).eq("player_id",state.currentPlayer.id);if(r.error)throw r.error;data=r.data||[];}const map=new Map(data.map(x=>[x.vote_date,x.choice]));$("#vote-days").innerHTML=dates().map(d=>{const k=iso(d),v=map.get(k);return `<article class="day-card"><div><span class="day-name">${esc(longFmt.format(d).split(" ")[0])}</span> <span class="day-date">${shortFmt.format(d)}</span></div><div class="vote-options">${Object.entries(choices).map(([c,m])=>`<button class="vote-button ${v===c?'selected':''}" data-date="${k}" data-choice="${c}" ${state.currentPlayer?'':'disabled'}>${m[0]}</button>`).join("")}</div></article>`}).join("");$$('[data-date]').forEach(b=>b.onclick=()=>saveVote(b.dataset.date,b.dataset.choice));}
async function saveVote(d,c){const r=await state.client.from("votes").upsert({week_start:iso(state.weekStart),vote_date:d,player_id:state.currentPlayer.id,choice:c},{onConflict:"vote_date,player_id"});if(r.error)return toast(errText(r.error),true);await loadVotes();}
async function summary(){const [vr,pr]=await Promise.all([state.client.from("votes").select("vote_date,choice,player_id").eq("week_start",iso(state.weekStart)),state.client.from("players").select("id,name,active").order("name")]);if(vr.error)throw vr.error;if(pr.error)throw pr.error;const vs=vr.data||[],map=new Map(vs.map(v=>[`${v.player_id}:${v.vote_date}`,v.choice])),ds=dates(),used=new Set(vs.map(v=>v.player_id)),ps=(pr.data||[]).filter(p=>p.active||used.has(p.id));$("#summary-content").innerHTML=`<div class="table-card"><table><thead><tr><th>Giocatore</th>${ds.map(d=>`<th>${longFmt.format(d).slice(0,3)}<br>${shortFmt.format(d)}</th>`).join("")}</tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.name)}</td>${ds.map(d=>{const v=map.get(`${p.id}:${iso(d)}`);return `<td><span class="vote-badge ${v||'empty'}">${v?choices[v][1]:'—'}</span></td>`}).join("")}</tr>`).join("")}</tbody></table></div>`;}
async function proposal(e){e.preventDefault();const title=$("#proposal-title").value.trim(),url=$("#proposal-url").value.trim(),notes=$("#proposal-notes").value.trim();const r=await state.client.from("game_proposals").insert({week_start:iso(state.weekStart),title,bgg_url:url||`https://boardgamegeek.com/geeksearch.php?q=${encodeURIComponent(title)}`,notes:notes||null,proposed_by_player_id:state.currentPlayer.id});if(r.error)return toast(errText(r.error),true);e.target.reset();await proposals();}
async function proposals(){const r=await state.client.from("game_proposals").select("id,title,bgg_url,notes,created_by,players(name)").eq("week_start",iso(state.weekStart));if(r.error)throw r.error;$("#proposal-list").innerHTML=(r.data||[]).map(x=>`<article class="list-card"><h3>${esc(x.title)}</h3><div class="meta">${esc(x.players?.name||"")}</div>${x.bgg_url?`<p><a href="${attr(x.bgg_url)}" target="_blank">BoardGameGeek ↗</a></p>`:''}</article>`).join("")||'<div class="empty-state">Nessuna proposta.</div>';}
async function ranking(){const r=await state.client.from("standings").select("player_name,wins,last_places,other_placements,presences,win_rate").order("wins",{ascending:false}).order("win_rate",{ascending:false});if(r.error)throw r.error;$("#ranking-content").innerHTML=`<table class="ranking-table"><thead><tr><th>#</th><th>Giocatore</th><th>Vittorie</th><th>Ultimi</th><th>Altri</th><th>Presenze</th><th>Win rate</th></tr></thead><tbody>${(r.data||[]).map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.player_name)}</strong></td><td>${x.wins}</td><td>${x.last_places}</td><td>${x.other_placements}</td><td>${x.presences}</td><td><strong>${Number(x.win_rate||0).toLocaleString('it-IT',{minimumFractionDigits:1,maximumFractionDigits:1})}%</strong></td></tr>`).join("")}</tbody></table>`;}
function fillResult(){const a=state.players.filter(p=>p.active),opts='<option value="">Scegli…</option>'+a.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");$("#result-winner").innerHTML=opts;$("#result-last").innerHTML=opts;$("#result-participants").innerHTML=a.map(p=>`<label class="participant-option"><input type="checkbox" name="participant" value="${p.id}"><span>${esc(p.name)}</span></label>`).join("");if(!$("#result-date").value)$("#result-date").value=iso(new Date());}
async function record(e){e.preventDefault();const participantIds=$$('[name="participant"]:checked').map(x=>x.value),winner=$("#result-winner").value,last=$("#result-last").value;if(participantIds.length<2)return toast("Seleziona almeno due partecipanti",true);if(!participantIds.includes(winner)||!participantIds.includes(last))return toast("Vincitore e ultimo devono essere partecipanti",true);const r=await state.client.rpc("admin_create_game_result",{p_played_on:$("#result-date").value,p_game_name:$("#result-game").value.trim(),p_bgg_url:$("#result-url").value.trim()||null,p_notes:$("#result-notes").value.trim()||null,p_winner_player_id:winner,p_last_player_id:last,p_participant_ids:participantIds});if(r.error)return toast(errText(r.error),true);e.target.reset();fillResult();await Promise.all([history(),ranking()]);toast("Risultato registrato");}
async function history(){const r=await state.client.from("game_history").select("id,played_on,game_name,bgg_url,notes,participants,created_at").order("played_on",{ascending:false});if(r.error)throw r.error;$("#history-list").innerHTML=(r.data||[]).map(x=>{const ps=Array.isArray(x.participants)?x.participants:[];return `<article class="list-card"><div class="list-card-header"><div><h3>${esc(x.game_name)}</h3><div class="meta">${histFmt.format(fromIso(x.played_on))} · ${ps.length} presenze</div></div>${state.isAdmin?`<button class="danger-button" data-del="${x.id}">Elimina</button>`:''}</div><div class="history-participants">${ps.map(p=>`<span class="participant-badge ${p.placement_role}">${p.placement_role==='winner'?'🏆':p.placement_role==='last'?'🔻':'•'} ${esc(p.player_name)}</span>`).join("")}</div>${x.notes?`<p>${esc(x.notes)}</p>`:''}</article>`}).join("");$$('[data-del]').forEach(b=>b.onclick=()=>delResult(b.dataset.del));}
async function delResult(id){if(!confirm("Eliminare il risultato?"))return;const r=await state.client.from("game_results").delete().eq("id",id);if(r.error)return toast(errText(r.error),true);await history();}
async function adminLogin(e){e.preventDefault();const r=await state.client.rpc("admin_login",{p_pin:$("#admin-pin").value});if(r.error||!r.data)return toast("PIN non valido",true);state.isAdmin=true;renderAdmin();}
async function adminLogout(){await state.client.rpc("admin_logout");state.isAdmin=false;renderAdmin();}
async function addPlayer(e){e.preventDefault();const r=await state.client.from("players").insert({name:$("#new-player-name").value.trim()});if(r.error)return toast(errText(r.error),true);e.target.reset();await players();renderPlayer();await adminPlayers();}
async function adminPlayers(){const r=await state.client.rpc("admin_list_players");if(r.error)throw r.error;$("#admin-player-list").innerHTML=(r.data||[]).map(p=>`<article class="list-card"><h3>${esc(p.name)}</h3><span class="pill">${p.active?'Attivo':'Archiviato'}</span></article>`).join("");}
function subscribe(){state.realtime=state.client.channel("live").on("postgres_changes",{event:"*",schema:"public",table:"game_results"},()=>loadTab()).on("postgres_changes",{event:"*",schema:"public",table:"game_result_participants"},()=>loadTab()).subscribe();}
function setWeek(d){state.weekStart=startWeek(d);weekUi();loadTab();}function shift(n){const d=new Date(state.weekStart);d.setDate(d.getDate()+n);setWeek(d)}function weekUi(){const ds=dates();$("#week-label").textContent=`${ds[0].getDate()} – ${histFmt.format(ds[6])}`;$("#week-input").value=weekValue(ds[0]);}function dates(){return Array.from({length:7},(_,i)=>{const d=new Date(state.weekStart);d.setDate(d.getDate()+i);return d})}function startWeek(x){const d=new Date(x);d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function fromIso(v){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d,12)}function weekValue(d){const t=new Date(d);t.setDate(t.getDate()+3-((t.getDay()+6)%7));const w1=new Date(t.getFullYear(),0,4),w=1+Math.round(((t-w1)/86400000-3+((w1.getDay()+6)%7))/7);return `${t.getFullYear()}-W${String(w).padStart(2,'0')}`}function weekMonday(v){const m=/^(\d{4})-W(\d{2})$/.exec(v);if(!m)return null;const d=startWeek(new Date(+m[1],0,4,12));d.setDate(d.getDate()+(+m[2]-1)*7);return d}function toast(m,e=false){const x=$("#toast");x.textContent=m;x.classList.toggle("error",e);x.classList.add("show");setTimeout(()=>x.classList.remove("show"),4000)}function errText(e){return e?.message||String(e)}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function attr(v){return esc(v)}
})();
